DROP TABLE product;

CREATE TABLE product (
    productid         NUMBER(7) PRIMARY KEY NOT NULL,
    productfname       VARCHAR2(255) NULL,
    productshortname    VARCHAR2(255) NOT NULL UNIQUE,
    productdept      VARCHAR2(255) NULL,
    producttype      VARCHAR2(255) NOT NULL,
    productdesc   VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE PID_SEQUENCE;

select * from product;

CREATE OR REPLACE PROCEDURE CREATE_PRODUCT (PFNAME IN VARCHAR2,
PSHORTNAME IN VARCHAR2, PDEPT IN VARCHAR2, PTYPE IN VARCHAR2, PDESC IN VARCHAR2)
AS BEGIN
INSERT INTO PRODUCT VALUES(PID_SEQUENCE.NEXT, PFNAME, PSHORTNAME, PDEPT, PTYPE, PDESC);
COMMIT;
END;
/

